
version: '3'
services:
  polling-station:
    restart: always
    build: .
    ports:
     - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
